<a href="https://colab.research.google.com/github/deviandinifebrianti/Machine-Learning/blob/main/TUGAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **TUGAS**

- Lakukan klasifikasi pada data MNIST dengan menggunakan model ANN
- Anda diperbolehkan melakukan eksplorasi terhadap,
  - Metode pra pengolahan
  - Pemilihan fitur
  - Arsitektur ANN
  - Fungsi Aktiviasi
- ANN diimplementasikan dengan menggunakan tensorflow.
- DIKERJAKAN SECARA BERKELOMPOK
- JELASKAN HASIL YANG ANDA DAPATKAN,
  - AKURASI
  - CONFUSION MATRIX
  - KONFIGURASI MODEL --> MULAI DARI PRA PENGOLAHAN SAMPAI ARSITEKTUR ANN

In [4]:
import tensorflow as tf
from keras import layers, models
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt

# Unduh dataset MNIST dari scikit-learn
mnist = fetch_openml('mnist_784')

# Pisahkan data gambar dan label
gambar = mnist.data.astype('float32')
label = mnist.target.astype('int')

# Langkah 1: Pra-pemrosesan
gambar /= 255.0  # Skalakan data

# Bagi data menjadi data pelatihan dan pengujian (split data)
train_images, test_images, train_labels, test_labels = train_test_split(
    gambar, label, test_size=0.2, random_state=42)

# Langkah 2: Definisikan arsitektur model ANN
model = models.Sequential([
    layers.Reshape(target_shape=(28, 28, 1), input_shape=(784,)),
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    layers.MaxPooling2D((2, 2)),
    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation='softmax')
])

# Langkah 3: Kompilasi model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Langkah 4: Latih model
history = model.fit(train_images, train_labels,
                    epochs=10, validation_split=0.2)

# Langkah 5: Akurasi
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f'Akurasi pada data pengujian: {test_acc:.2f}')

/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


Epoch 1/10
1400/1400 [==============================] - 23s 16ms/step - loss: 0.1802 - accuracy: 0.9455 - val_loss: 0.0718 - val_accuracy: 0.9779
Epoch 2/10
1400/1400 [==============================] - 18s 13ms/step - loss: 0.0567 - accuracy: 0.9821 - val_loss: 0.0687 - val_accuracy: 0.9779
Epoch 3/10
1400/1400 [==============================] - 19s 13ms/step - loss: 0.0364 - accuracy: 0.9883 - val_loss: 0.0560 - val_accuracy: 0.9827
Epoch 4/10
1400/1400 [==============================] - 18s 13ms/step - loss: 0.0241 - accuracy: 0.9921 - val_loss: 0.0554 - val_accuracy: 0.9835
Epoch 5/10
1400/1400 [==============================] - 19s 13ms/step - loss: 0.0172 - accuracy: 0.9946 - val_loss: 0.0538 - val_accuracy: 0.9845
Epoch 6/10
1400/1400 [==============================] - 18s 13ms/step - loss: 0.0128 - accuracy: 0.9958 - val_loss: 0.0649 - val_accuracy: 0.9843
Epoch 7/10
1400/1400 [==============================] - 19s 13ms/step - loss: 0.0112 - accuracy: 0.9965 - val_loss: 0.0514 -

Penjelasan:
1. Pra-pemrosesan

- Pada langkah ini dilakukan untuk mengubah rentang nilai piksel gambar dari [0, 255] menjadi [0, 1] atau [0, 255] menjadi [0, 255] sesuai kebutuhan.
- Membagi data gambar dan label ke dalam dua set terpisah (data pelatihan dan data pengujian)

2. Akurasi tersebut menunjukkan akurasi yang tinggi, sehingga dapat dikatakan bahwa akurasi 0.98 dapat memprediksi data dengan baik

In [ ]:
# Evaluasi akurasi data pelatihan
train_loss, train_acc = model.evaluate(train_images, train_labels)
print(f'Akurasi pada data pelatihan: {train_acc:.2f}')

1750/1750 [==============================] - 6s 4ms/step - loss: 0.0167 - accuracy: 0.9954
Akurasi pada data pelatihan: 1.00


In [ ]:
from sklearn.metrics import confusion_matrix

# Membuat prediksi pada data pengujian
predictions = model.predict(test_images)
predicted_labels = np.argmax(predictions, axis=1)

# Membuat matriks kebingungan
confusion = confusion_matrix(test_labels, predicted_labels)
print('Matriks Kebingungan:')
print(confusion)

438/438 [==============================] - 2s 4ms/step
Matriks Kebingungan:
[[1335    0    1    0    0    2    2    1    2    0]
 [   1 1588    1    1    0    1    1    4    1    2]
 [   0    6 1350    3    4    1    0   10    4    2]
 [   0    0    3 1406    0   12    0    6    2    4]
 [   1    0    1    0 1284    1    0    2    1    5]
 [   0    2    0    6    0 1262    2    0    1    0]
 [   3    2    0    0    4    7 1378    0    2    0]
 [   2    3    2    0    4    0    0 1489    0    3]
 [   1    3    4    7    0    6    3    4 1319   10]
 [   3    1    1    1   14   14    0    5    4 1377]]


Penjelasan:
1. Evaluasi Model pada Data Pengujian
untuk mengetahui seberapa baik model yang dijalankan dalam melakukan klasifikasi pada data baru dan tidak terlihat sebelumnya setelah mengevaluasi model pada data pengujian

2. Confusion Matrix
- Matriks yang digunakan untuk mengevaluasi kinerja dari suatu model klasifikasi
- Matriks kebingungan tersebut memiliki 10 baris dan 10 kolom. Cara bacanya adalah dari atas ke bawah dan dari kiri ke kanan