<a href="https://colab.research.google.com/github/deviandinifebrianti/Machine-Learning/blob/main/Praktikum_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PRAKTIKUM 4

**PRA PENGOLAHAN DATA**

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

## Load Data

In [6]:
#mengupload dataset yang akan digunakan
from google.colab import files
uploaded = files.upload()

Saving Churn_Modelling.csv to Churn_Modelling.csv


## Cek Data (X)

In [7]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values
#Cek data X
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


## Encoding Data Kategorikal

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
#Cek data(X)
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


## Encoding Kolom "Geography" dengan One Hot Encoder



In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


## Split Data

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Scaling Fitur

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# MEMBUAT MODEL ANN

## Inisiasi Model ANN

In [12]:
ann = tf.keras.models.Sequential()

## Membuat IInput Layer dan Hiddenn Layer Pertama

In [13]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

## Membuat Hidden Layer Kedua

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

## Membuat Output Layer

In [15]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# TRAINING MODEL

## Compile Model (Menyatukan Arsitektur) ANN

In [16]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

## Fitting Model

In [17]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 3s 5ms/step - loss: 0.5610 - accuracy: 0.7439
Epoch 2/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4511 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4312 - accuracy: 0.7961
Epoch 4/100
250/250 [==============================] - 2s 6ms/step - loss: 0.4201 - accuracy: 0.7976
Epoch 5/100
250/250 [==============================] - 1s 6ms/step - loss: 0.4089 - accuracy: 0.8135
Epoch 6/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3952 - accuracy: 0.8292
Epoch 7/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3817 - accuracy: 0.8393
Epoch 8/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3727 - accuracy: 0.8438
Epoch 9/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3667 - accuracy: 0.8468
Epoch 10/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3623 - accura

# MEMBUAT PREDIKSI
Diberikan informasi sebagai berikut,

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: $60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: $50000

Apakah customer tersebut perlu dipertahankan?

## Modelkan Data Baru dan Buat Prediksi

In [18]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 364ms/step
[[False]]


## Prediksi dengan Data Testing

In [19]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


## Cek Akurasi dan Confusion Matrix

In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1508   87]
 [ 197  208]]


0.858